### ISSUE TITLE
Update the comparison table

### ISSUE THREAD

**Issue by ratson** [grantila/awesome-phonenumber#1]
The latest version of `google-libphonenumber` is 1.0.7, the comparison in README seems a little bit old.
I am wondering anything has changed.

It would be great if a benchmark script could be added, so others could try and see the difference on their machines.

**Comment by grantila** [comment]
Maybe the comparison table put some pressure on the other libs, as `google-libphonenumber` has improved a lot. It's now both loads faster, runs faster, and is smaller. You're welcome ;)

I updated the README to the latest versions of both `google-libphonenumber` and `node-phonenumber`, and you also have the benchmark script yourself now.

**Comment by ratson** [comment]
@grantila Thank you for the great work, good that I could test it now.

FYI, here is the result I run with Node v5.2.0, both `google-libphonenumber` and `awesome-phonenumber` performed well.
```
Testing speeds of google-libphonenumber
{ load: 46.52,
  parse: 9.68,
  mem: 13874298.88,
  time: 1101.4,
  files: 32,
  size: '2.3M' }
Testing speeds of node-phonenumber
{ load: 155.2,
  parse: 14.06,
  mem: 17597399.04,
  time: 6433,
  files: 4355,
  size: ' 53M' }
Testing speeds of awesome-phonenumber
{ load: 31.64,
  parse: 10.42,
  mem: 6542540.8,
  time: 974.6,
  files: 7,
  size: '244K' }
```

**Comment by grantila** [comment]
I'm on 5.1, and also `awesome-phonenumber` now uses 7.2.1 while `google-libphonenumber` is still on 7.1. Both if these can contribute to the run-time compilation from the other libraries to result in faster code.

I did bump it up to 100 iterations for smaller errors, and added a test for how long it takes to parse the second phone number, when all code is "warmed up" (cached regexes etc). That was pretty interesting ;)

Anyway, now that this is a bit more automated, I'll try to keep this table up-to-date with newer versions of `libphonenumber` and the npm packages.

**Comment by ruimarinho** [comment]
@grantila, I was unaware that these benchmarks existed but unexpectedly they are very biased. It's literally comparing apples to oranges as the table omits the fact that `google-libphonenumber` is simply a wrapper for `libphonenumber` and also ships with browser compliant versions, as well as their minified builds. It is also pre-compiled (doesn't depend on closure compiler), which your README fails to clarify.  

In constrast, your library builds on top of `libphonenumber` by adding it's own API. Most performance improvements come from caching parsed values which you could very well do using `google-libphonenumber` as your base lib.

The number of files is also a non-sense measure as those are published to help other developers explore the package without having to go through github just to take a glance at the tests or configuration settings. Have you tried debugging `lib/index.js` on your lib?

Last but not least, why don't you submit your performance improvements to https://github.com/googlei18n/libphonenumber so we can all benefit from them?
