### ISSUE TITLE
Bump to libphonenumber v8.0.1

### ISSUE THREAD

**Issue by FrikkieRetro** [grantila/awesome-phonenumber#10]
Hi

So libphonenumber released v8.0.1, and it has the fix for #9 .

Is there any timeline on when the bump can be expected?

https://github.com/googlei18n/libphonenumber/releases/tag/v8.0.1

**Comment by grantila** [comment]
Thanks for letting me know! Bumped in 1.2.0.

**Comment by FrikkieRetro** [comment]
Awesome thanks!
