### ISSUE TITLE
Phone number ending with special characters considered as valid

### ISSUE THREAD

**Issue by zoltantakacs-born** [grantila/awesome-phonenumber#100]
For the input `+1 202-918-2132+-@£$%^!` `parsePhoneNumber` returns this result:
```json
{
    "number": {
        "input": "+1 202-918-2132+-@£$%^!",
        "international": "+1 202-918-2132",
        "national": "(202) 918-2132",
        "e164": "+12029182132",
        "rfc3966": "tel:+1-202-918-2132",
        "significant": "2029182132"
    },
    "regionCode": "US",
    "valid": true,
    "possible": true,
    "canBeInternationallyDialled": true,
    "type": "fixed-line-or-mobile",
    "possibility": "is-possible",
    "typeIsMobile": true,
    "typeIsFixedLine": true,
    "countryCode": 1
}
```

If you add any special character after a valid phone number it is still considered to valid input.

I would expect it to interpret it as invalid input.

**Comment by grantila** [comment]
This is intentional by libphonenumber. I'm not sure the underlying reasoning for that decision, but it's mentioned here: https://github.com/google/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits
