### ISSUE TITLE
Parse German phone number not working currently in specific numbers

### ISSUE THREAD

**Issue by NetanelCarmen** [grantila/awesome-phonenumber#101]
When i try to parse the number "491773333333" with region code 'DE' this is the result i'm receiving
as you can see for some reason the parse does not remove the country code for the national number and added the country code again in the other numbers

actual:
```
{
    "number": {
        "input": "491773333333",
        "international": "+49 491 773333333",
        "national": "0491 773333333",
        "e164": "+49491773333333",
        "rfc3966": "tel:+49-491-773333333",
        "significant": "491773333333"
    },
    "regionCode": "DE",
    "valid": true,
    "possible": true,
    "canBeInternationallyDialled": true,
    "type": "fixed-line",
    "possibility": "is-possible",
    "typeIsMobile": false,
    "typeIsFixedLine": true,
    "countryCode": 49
}
```
expected:
```
{
    "number": {
        "input": "491773333333",
        "international": "+49 177 3333333",
        "national": "0177 3333333",
        "e164": "+491773333333",
         ...
    },
    ...
}
```

and when I'm trying to parse the number "4989333333333" with the same region code its not reproducing 

```
{
    "number": {
        "input": "4989333333333",
        "international": "+49 89 333333333",
        "national": "089 333333333",
        "e164": "+4989333333333",
        "rfc3966": "tel:+49-89-333333333",
        "significant": "89333333333"
    },
    "regionCode": "DE",
    "valid": true,
    "possible": true,
    "canBeInternationallyDialled": true,
    "type": "fixed-line",
    "possibility": "is-possible",
    "typeIsMobile": false,
    "typeIsFixedLine": true,
    "countryCode": 49
}
```

I'm using version 4.4.1 and i can't update to version 5 due to our node version, however, I checked in the change log and it seems that there is no mention of that in the new versions

**Comment by grantila** [comment]
491773333333 is not the phone number you think it is. If you add a "+" in front of it, it's valid E164 (and then you don't need to specify region code).
If you want to specify region code and _not_ provide an E164 number, then remove "49" from the beginning.
