### ISSUE TITLE
Not correct validation for south africa county

### ISSUE THREAD

**Issue by rishit128** [grantila/awesome-phonenumber#102]
After selecting south Africa country i have enter +2784545 and it gave valid true. For south Africa there should be minimum 9 digit mobile number.
const {valid} = parsePhoneNumber( '+2784545' );
it return as valid true for south Africa.

**Comment by grantila** [comment]
This would be a bug in upstream [libphonenumber](https://github.com/google/libphonenumber), so you'll have to report it there
