### ISSUE TITLE
Bug: French number (+33) starting with 71 / 72

### ISSUE THREAD

**Issue by snack-0verflow** [grantila/awesome-phonenumber#104]
## Context

During our product development, we've noticed French number (`+33`) starting with `71` or `72` seem to fail validation. Just wanted to raise a ticket here before raising a ticket at `libphonenumber`. 

I believe this might be a Google's library problem rather this package.

Let me know what you folks think!

## Version

`5.10.0`

## Test examples

```
+33716482217 ❌
+33726482217 ❌
+33756482217 ✅
```

**Comment by grantila** [comment]
Yeah, this is most likely an issue in libphonenumber, if these numbers are actually even possible. Go ahead and report it here: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue
