### ISSUE TITLE
Update: Google libphonenumber version

### ISSUE THREAD

**Issue by YinianFan** [grantila/awesome-phonenumber#105]
Since carrier data has been updated for country calling nodes, some customers' phone number validates fails in the latest version of this package. But the newest version of Google libphonenumber has included these phone numbers.
As Google libphonenumber has published a new version of v8.3.19 last week, do you have a plan to update it to the newest version?

### Version
`5.10.0`

### Test Example
`+658075XXXX`

**Comment by grantila** [comment]
Latest should be .21 which solves this, thanks for reporting!
