### ISSUE TITLE
Bug: Falesly mark invalid numbers as valid

### ISSUE THREAD

**Issue by abzokhattab** [grantila/awesome-phonenumber#109]
Hello there, 

I am trying to run `parsePhoneNumber` on the following number: 
which is an invalid number: 
`+115005550009`

and here is the output:

![](https://user-images.githubusercontent.com/59809993/271655799-a3c69e3f-8a07-4e58-9034-63663a057e60.png)

shouldnt it show an invalid and not possible number?

cc @grantila

**Comment by grantila** [comment]
It's valid according to upstream libphonenumber: https://libphonenumber.appspot.com/phonenumberparser?number=%2B115005550009

So if this is wrong, it needs to be reported as a bug to libphonenumber: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue
