### ISSUE TITLE
6-digit EU-numbers

### ISSUE THREAD

**Issue by vegarda** [grantila/awesome-phonenumber#112]
Will you support 6-digit EU-numbers?

https://en.wikipedia.org/wiki/Short_code#European_Union

https://nkom.no/telefoni-og-telefonnummer/telefonnummer-og-den-norske-nummerplan/alle-nummerserier-for-norske-telefonnumre#6sifrede_esharmoniserte_nummer

https://libphonenumber.appspot.com/phonenumberparser?number=116117&country=NO

> Short Number Results
> Result from isPossibleShortNumber()	true
> Result from isValidShortNumber()	true
> Result from isPossibleShortNumberForRegion()	true
> Result from isValidShortNumberForRegion()	true

**Comment by grantila** [comment]
Not unless upstream libphonenumber supports it, as it doesn't seem to do now. Whenever a new libphonenumber is released with support for this, awesome-phonenumber will too!

**Comment by grantila** [comment]
Sorry, missed that this is handled differently in libphonenumber, will look into it.

**Comment by grantila** [comment]
This is now available as the boolean fields `shortPossible` and `shortValid`.
