### ISSUE TITLE
getExample causes a runtime error on some countries

### ISSUE THREAD

**Issue by adamhinckley** [grantila/awesome-phonenumber#113]
One example of this

```
getExample("AQ")  //Antarctica

```

This is an issue in my case because we want to have every country on earth available in our phone input.  I realize this library likely isn't intended work for every country on earth, but I would like to not get a runtime error when an obscure place like Antarctica is selected.

Thanks!

**Comment by adamhinckley** [comment]
Mistake on my part: I failed to realize that `getSupportedRegionCodes` was something I could use only allow for supported countries to be used in the input.

**Comment by grantila** [comment]
No worries, glad you figured it out!
