### ISSUE TITLE
Inconsistent formatting of international phone numbers

### ISSUE THREAD

**Issue by sayinmehmet47** [grantila/awesome-phonenumber#119]
I have noticed that the library formats some phone numbers correctly, but others are not formatted as expected.

Here is an example:

```js
const pn1 = parsePhoneNumber('+41 7777772');
const pn2 = parsePhoneNumber('+33792193286');

console.log('phone1', pn1.number?.international);
console.log('phone2', pn2.number?.international);`
```

`phone1 +41 7777772
phone2 +33 7 92 19 32 86`

I would like both phone numbers to be formatted like +33 7 92 19 32 86, but the Swiss phone number (+41 7777772) is not being formatted correctly.

Could you please help me understand why this is happening and how I can get consistent formatting for all phone numbers?

Thank you for your assistance.

**Comment by grantila** [comment]
Looks like this is from upstream libphonenumber: [phone1](https://libphonenumber.appspot.com/phonenumberparser?number=%2B417777772) and [phone2](https://libphonenumber.appspot.com/phonenumberparser?number=%2B33792193286)

FYI, the first phone number isn't valid.

If it's an issue, this must be reported to libphonenumber: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue
