### ISSUE TITLE
Is it possible to find the country of a given full phone number?

### ISSUE THREAD

**Issue by finferflu** [grantila/awesome-phonenumber#12]
For example:

`PhoneNumber.getCountry('+441618811234')`

Output:

`UK`

Having to specify the country when initialising a phone number can be counter-productive when you don't know where the number is from. 

Thanks!

**Comment by grantila** [comment]
If the number you provide is prefixed `+`, `awesome-phonenumber` will try to detect the country automatically.

```js
const PhoneNumber = require( "awesome-phonenumber" );

const pn = new PhoneNumber( '+441618811234' );
const cc = pn.getRegionCode( ); // "GB"
```

or shortcut:

```js
const cc = PhoneNumber( '+441618811234' ).getRegionCode( );
```

**Comment by finferflu** [comment]
Thanks for the very quick answer, very much appreciated. I think the documentation should make this a bit clearer, as I thought I couldn't initialise the PhoneNumber object without specifying the country. Given such possibility, this module becomes 100% more useful to me. Thanks again!

**Comment by grantila** [comment]
Noted and fixed, thanks for the feedback!

**Comment by finferflu** [comment]
You're welcome, and thanks!
