### ISSUE TITLE
Canadian 310-XXXX toll free numbers recognized as legal US numbers?

### ISSUE THREAD

**Issue by gosnat-bethel** [grantila/awesome-phonenumber#120]
With a region code of "US", most of the time a legal phone number involves 10 digits (3 for area code, 7 for the local number).  This makes sense.

However, any number starting with "310" will validate with only 7 digits (so no area code required).

After a tiny bit of investigation, it looks like in Canada, a number starting with "310" is some sort of local-only toll-free number so that rule would make sense for region code "CA", but why does it also match for region code "US" where 310 is an area code in California and should require 10 digits?

**Comment by grantila** [comment]
I'm pretty sure this is an upstream issue with libphonenumber if anything. Please report it to libphonenumber: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue

**Comment by gosnat-bethel** [comment]
Thanks.  I notice that there's already this issue, so I'll hold off on filing another one:

https://issuetracker.google.com/issues/335892662
