### ISSUE TITLE
Input phone number is being modified when parsed

### ISSUE THREAD

**Issue by dnechay** [grantila/awesome-phonenumber#121]
Hey 👋🏼 
Thank you for this amazing library!

Recently we found out a weird behavior and would like to clarify if it's a potential bug in the lib.

If we take `+112058876531` as an example input phone number and do `parsePhoneNumber` on it, this is what we get as a result
```
{
  number: {
    input: '+112058876531',
    international: '+1 205-887-6531',
    national: '(205) 887-6531',
    e164: '+12058876531',
    rfc3966: 'tel:+1-205-887-6531',
    significant: '2058876531'
  },
  regionCode: 'US',
  valid: true,
  possible: true,
  canBeInternationallyDialled: true,
  possibility: 'is-possible',
  type: 'fixed-line-or-mobile',
  typeIsMobile: true,
  typeIsFixedLine: true,
  countryCode: 1
}
```
You can notice that it removes `1` at the very beginning of the string (not international `+1`, but the next one) and claims that the number is valid.

That behavior leads to inconsistencies in what you get after using the library.

Could you please clarify if it's expected behavior or am I missing something?

That is input by our user and we expect that it returns "invalid" in this case because US area codes do not start with `1` ([ref](https://www.allareacodes.com/area_code_listings_by_state.htm))

TIA

**Comment by grantila** [comment]
Hi! Looks like this is how upstream libphonenumber works if you check this output: https://libphonenumber.appspot.com/phonenumberparser?number=%2B112058876531

Report it here if you think it's a bug: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue as awesome-phonenumber doesn't alter how libphonenumber works

**Comment by dnechay** [comment]
Hey @grantila !
Indeed, it seems to be upstream library behavior (https://issuetracker.google.com/issues/350526067)

However, by some reason there is a difference in output for that specific case when more than one digit is prefixed.
Let's take `+1112058876531` as an example
Upstream library behavior - https://libphonenumber.appspot.com/phonenumberparser?number=%2B1112058876531
<img width="806" alt="Screenshot 2024-07-05 at 11 19 01" src="https://github.com/grantila/awesome-phonenumber/assets/15381780/06fdee43-7521-4295-8551-ee0ac0f8328d">
what this library returns:
```
{
  number: {
    input: '+1112058876531',
    international: '+1 12058876531',
    national: '12058876531',
    e164: '+112058876531',
    rfc3966: 'tel:+1-12058876531',
    significant: '12058876531'
  },
  regionCode: 'US',
  valid: false,
  possible: false,
  canBeInternationallyDialled: true,
  possibility: 'too-long',
  type: 'unknown',
  typeIsMobile: false,
  typeIsFixedLine: false,
  countryCode: 1
}
```

Shouldn't it return `null` or `invalid` for `e164` in this case?
