### ISSUE TITLE
Metadata uptodate?

### ISSUE THREAD

**Issue by stephanebarbey** [grantila/awesome-phonenumber#14]
Hi,

I am having a trouble with some numbers, e.g. +1613 734.6759, which returns US as region instead of CA, whereas the "original" google returns the correct region code (CA). (google-libphonenumber returns the correct region code :-) ).

Any idea why this is wrong?

Thanks,
-Stephane

**Comment by grantila** [comment]
You mean when you **explicitly** say `'CA'` as region code, `awesome-phonenumber` forces it to`'US'`? That's surely a bug, and I have a patch on the way.
