### ISSUE TITLE
TSlint failed

### ISSUE THREAD

**Issue by UrielCh** [grantila/awesome-phonenumber#18]
Hi,

I import awesome-phonenumber in my TS code with:

    import Phonenumber = require("awesome-phonenumber");

and I get this error from tslint:
[ts] Cannot use 'new' with an expression whose type lacks a call or construct signature.

I found the same error on this page project [Fuse](https://github.com/krisk/Fuse):
[PR](https://github.com/krisk/Fuse/pull/129)
so I solve It on *awesome-phonenumber* like this commit.
[commit](https://github.com/krisk/Fuse/commit/4f6b9b2c5eb607e9a079c0a1619e0f5b278ac5f5)

I remove the error by changing index.d.ts

as:

```
export as namespace AwesomePhonenumber;
export = PhoneNumber;

declare type PhoneNumberFormat =
	'e164' |
	'international' |
	'national' |
	'rfc3966' |
	'significant';

declare type PhoneNumberTypes =
	'fixed-line' |
	'fixed-line-or-mobile' |
	'mobile' |
	'pager' |
	'personal-number' |
	'premium-rate' |
	'shared-cost' |
	'toll-free' |
	'uan' |
	'voip' |
	'unknown';

declare class PhoneNumber
{
	constructor( phoneNumber: string, countryCode?: string );

	isValid( ): boolean;
	canBeInternationallyDialled( ): boolean;
	isPossible( ): boolean;
	getType( ): PhoneNumberTypes;
	isMobile( ): boolean;
	isFixedLine( ): boolean;
	getNumber( type?: PhoneNumberFormat ): string;
	getNumberFrom( regionCode: string ): string;
	getRegionCode( ): string;
	toJSON( ): any;

	static getCountryCodeForRegionCode( regionCode: string ): number;
	static getRegionCodeForCountryCode( countryCode: number ): string;
	static getSupportedCallingCodes( ): string[ ];
	static getExample( regionCode: string, type?: PhoneNumberTypes ): PhoneNumber;
	static getAsYouType( regionCode: string ): AsYouType;
}

declare class AsYouType
{
	addChar( char: string ): string;
	number( ): string;
	removeChar( ): string;
	reset( number?: string ): string;
	getPhoneNumber( ): PhoneNumber;
}
```

**Comment by grantila** [comment]
May I just ask why you import with `require` instead `from`? Like
```ts
import Phonenumber from "awesome-phonenumber"
```

**Comment by UrielCh** [comment]
Good question...

I start my code as an ES6 javascript and then convert it to typescript, this is my only import statement using a *require*;

But in my case, I use Typescript, and with a *from* It working perfectly.

Maybe this change can be useful if using without transcoding.

**Comment by grantila** [comment]
I think the difference might be that Fuse isn't ES6-default-exported, and so it **must** be imported with `require`, which is unfortunate. The world is moving towards `import`, so I'll keep it like this for now. If further issues appear, I'm glad you provided a solution, thanks.

**Comment by aluanhaddad** [comment]
You don't need to use `require` but it's the best option if you're using CommonJS modules. Otherwise check out the `--esModuleInterop` flag and use the synthetic default. The main thing is to avoid `import * as ns from "m";` at all costs when the module source code is an AMD, UMD, or CJS module.

**Comment by grantila** [comment]
@aluanhaddad how `import * as ns from "m";` is worse than `require` beats me. Are we supposed to 1) have both `require` and `import` in our modern source code, and 2) somehow be expected to *know* whether the module we depend on (from, say, npmjs) is CJS or ES6? What if it changes?
