### ISSUE TITLE
a.charAt is not a function

### ISSUE THREAD

**Issue by BowserV2** [grantila/awesome-phonenumber#19]
when calling for it to verify the number i get  `a.charAt is not a function`

**Comment by grantila** [comment]
Could you provide the exact code you run to get this behaviour?

**Comment by grantila** [comment]
Closing this issue for housekeeping purposes

**Comment by gcphost** [comment]
I was having this issue when I was passing a wrapped number for validation.

```
const number = awesomePhoneNumber('+15125550000');
awesomePhoneNumber(number).isValid();
```

I was doing some validation with the number and failed to realize this was occurring.
