### ISSUE TITLE
getExample returns the same number per region

### ISSUE THREAD

**Issue by piotrgorecki** [grantila/awesome-phonenumber#21]
Hi,

Every time when I call `getExample` I obtain the same phone number. I thought that this will be randomized, or at least, the same sequence of different numbers. Are those examples hardcoded?

```js
var PhoneNumber=require("awesome-phonenumber");

console.log(PhoneNumber.getExample("PL").getNumber());
console.log(PhoneNumber.getExample("PL").getNumber());
console.log(PhoneNumber.getExample("PL").getNumber());
console.log(PhoneNumber.getExample("SE").getNumber());
console.log(PhoneNumber.getExample("SE").getNumber());
console.log(PhoneNumber.getExample("PL").getNumber());
```
```
+48123456789
+48123456789
+48123456789
+468123456
+468123456
+48123456789
```

**Comment by grantila** [comment]
This functionality comes from Google's libphonenumber (which awesome-phonenumber is just a [precompiled] frontend to), so you'd have to convince Google to implement this randomness: https://github.com/googlei18n/libphonenumber#highlights-of-functionality ;)
