### ISSUE TITLE
Question about managing number of digits in phone number

### ISSUE THREAD

**Issue by imsam67** [grantila/awesome-phonenumber#22]
Hi,

This is not really an issue but a question. I see that there are API methods that indicate whether a number is too short or too long. I suspect this is because not every country in the world necessarily has a fixed number of digits in its phone numbers. Is that the case?

What's the best way to use this library to disallow extra digits as the user enters numbers. For example, in the U.S, it's always 3 digits for the area code and 7 digits for the number, a total of 10 digits -- without separating characters. I want to prevent the user from entering more than 10 digits. Do I check for both too long and too short as the user types in the number?

Thanks,
Sam

**Comment by grantila** [comment]
First question yes, in many cases the length can vary depending on domestic prefixes e.g.

Second, it's up to you. Either mark the input as invalid, make it red, disable the "Ok" button or whatever if the phone number isn't valid.
I'd not spend time trying to limit the number of characters one can input but rather check for validity and allow/disallow continuing based on that.
