### ISSUE TITLE
Unable to use API functions

### ISSUE THREAD

**Issue by imsam67** [grantila/awesome-phonenumber#23]
I created a bunch of util functions as wrappers to your library but for some reason, they're not working.

The behavior I'm getting while using `AsYouType` is that after entering the second digit, I get undefined but interestingly it's formatted like a US phone number -- and I'm entering a US phone number. Here's what it looks like:
![capture](https://user-images.githubusercontent.com/15844030/36081955-72186930-0f6a-11e8-9873-c296ea4e141c.PNG)

I'm having problems with other wrapper functions as well. Clearly, I'm making a mistake somehwere.

Here's what my util functions looks like:

```
let PhoneNumber = require('awesome-phonenumber');

export const formatPhoneNumberAsYouType = (input, countryId) => {
    
    const output = new PhoneNumber.getAsYouType(countryId.toUpperCase());
    output.addChar(input);

    return output.number();
}

export const unformatPhoneNumber = (input, countryId) => {

    const pn = new PhoneNumber(input, countryId.toUpperCase());

    return pn.getPhoneNumber('significant');
}
```

What am I doing wrong here?

**Comment by grantila** [comment]
1. Remove the `new` in the first function
2. The as-you-type formatting in libphonenumber requires one character at a time, so in the first function, you'll need to iterate `input` char-by-char, if it's a string of multiple characters: `input.split( '' ).forEach( char => output.addChar(char) );`
3. In the second function, it's not `getPhoneNumber`, but [`getNumber`](https://www.npmjs.com/package/awesome-phonenumber#basic-usage)

**Comment by spacesuitdiver** [comment]
@grantila instead of iterating can't you just use `reset(input)`?

**Comment by grantila** [comment]
Closing for house-keeping purposes
