### ISSUE TITLE
Can I use a specific formatter with AsYouType?

### ISSUE THREAD

**Issue by spacesuitdiver** [grantila/awesome-phonenumber#24]
It seems AYT defaults to international formatter? Is it possible to use national?

**Comment by grantila** [comment]
Sounds weird, you do specify which region code to use, as in the example:

```js
var ayt =  PhoneNumber.getAsYouType( 'SE' ); // For Swedish numbers
```

and underneath it uses the `libphonenumber` as-you-type formatter which uses this region code for the formatting. Do you have an example?

**Comment by FrenchMajesty** [comment]
Yes, I have an example.
```
const formatter = PhoneNumber.getAsYouType('US');
formatter.reset('817 378 73');
```

The following should output the string `(817) 378-73` but instead it comes out as `817-37873`.

**Comment by grantila** [comment]
@FrenchMajesty why are you adding spaces? The as-you-type (again, doing *exactly* what Google's libphonenumber is doing) is supposed to be used for things like typing the number on a mobile phone, and then filtering it through libphonenumber before printing it on the screen.

```js
const formatter = PhoneNumber.getAsYouType('US');
formatter.reset('81737873'); // "(817) 378-73"
```

After some googling I found that `inputDigit` (which awesome-phonenumber calls on libphonenumber) is [documented](https://static.javadoc.io/com.googlecode.libphonenumber/libphonenumber/8.5.2/com/google/i18n/phonenumbers/AsYouTypeFormatter.html#inputDigit-char-) like this:

> nextChar - the most recently entered digit of a phone number. Formatting characters are allowed, but as soon as they are encountered this method formats the number as entered and not "as you type" anymore. Full width digits and Arabic-indic digits are allowed, and will be shown as they are.

So, by adding a non-numeric (*formatting*) character, the type of formatting will change from the preferred country format into some other custom format.

Quickest fix would be to `.reset(text.replace(/ /g, ''))`
