### ISSUE TITLE
There isn't a way to get INVALID_COUNTRY_CODE etc.

### ISSUE THREAD

**Issue by RazerM** [grantila/awesome-phonenumber#26]
I don't think it's possible to get `INVALID_COUNTRY_CODE` or `TOO_SHORT` from this library, is it?

The parse error is swallowed:

https://github.com/grantila/awesome-phonenumber/blob/0b30048baa3ce726a0372b70a89f9a67279c0fb3/src/index.js#L151-L158

**Comment by grantila** [comment]
The `TOO_SHORT` doesn't end up in that catch. A too short number will end up with:
`pn.possibility === 'too-short'` already

The invalid country code handling hasn't been correct though, that's true.

Fixed and validated: https://github.com/grantila/awesome-phonenumber/blob/master/test.in/awesome-phonenumber/should-compile.ts#L85-L120
