### ISSUE TITLE
Stand alone version

### ISSUE THREAD

**Issue by qasim90** [grantila/awesome-phonenumber#27]
Is there any stand alone version available that can be used without many other dependencies???

**Comment by steelbrain** [comment]
Two things

- More than one question marks, ie. `???` are extremely rude, please try not to use them
- There are already no dependencies, at least not npm ones. There are devDependencies but they shouldn't be installed when you are including this package in your project, see https://github.com/grantila/awesome-phonenumber/blob/e88e919000587beda26e3171a36b2a818a79f0ad/package.json#L38

Can you please link a source to back your claim of this project having **many other** dependencies?
