### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by ridgekimani** [grantila/awesome-phonenumber#28]
[This package](https://www.jsdelivr.com/package/npm/awesome-phonenumber) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by kangchals** [comment]
I think 3.0 means it will be added on 3.0 version. Is it right? @grantila 
Could you tell me when 3.0 version comes approximately? Thank you!
