### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Dexus** [grantila/awesome-phonenumber#3]
Hey can you update the lib?

And can you create a build howto, what deps need etc?

**Comment by Dexus** [comment]
#4

**Comment by grantila** [comment]
You should only need to run `gulp` to build, but google changed from googlecode to github, so the url's weren't working anymore I suppose. Would've been able to merge your PR if you hadn't changed the coding style completely, especially blended with logic changes...

Anyway, fixed.
