### ISSUE TITLE
Get region code requiring more digits that it should

### ISSUE THREAD

**Issue by Yhozen** [grantila/awesome-phonenumber#30]
https://github.com/grantila/awesome-phonenumber/blob/c36c32394c0ca7275f9db2f132a5a49caec15e0e/src/index.js#L72-L96

As we can see on that snippet, to get the region code we need to write 4 digits but it's only taking into account the first 3, can we switch it to just 3?

**Comment by grantila** [comment]
Right, don't remember why, do you have a use case for only 4 characters? Are you detecting on-the-fly while people enter a phone number?

**Comment by Yhozen** [comment]
Yes I'm trying to show the corresponding flag as they type, and it's working but it's probably a better user experience to show asap
