### ISSUE TITLE
Wrong recognition of region code

### ISSUE THREAD

**Issue by omerts** [grantila/awesome-phonenumber#31]
Currently the region code recognition, takes into account the first 4 digits, as minimum as possible, in order to try to figure out the region code. This is problematic for shared region codes such as 1, that is used both for US and Canada. This means that currently, no Canadian number is recognized as such, unless an explicit country code is passed.

**Comment by omerts** [comment]
Created PR #32

**Comment by grantila** [comment]
Oh, sounds related to #30

**Comment by grantila** [comment]
I want to minimize the number of `parse` calls to libphonenumber to make this as fast as possible so I have a similar fix ongoing.
