### ISSUE TITLE
False positive brazilian phone number

### ISSUE THREAD

**Issue by Mateusspadacio** [grantila/awesome-phonenumber#34]
This phone number ```551175757575``` is an invalid brazilian phone number, but the method ```isMobile()``` is returning true because of its first number 7 after brazilian DDD.
The others phone numbers such as ```551185757575``` are returning false correctly.

Example code
```
const PhoneNumber = require( 'awesome-phonenumber' );

const pn = new PhoneNumber( '+551185757575', 'ZZ' );
console.log(pn.isMobile()); // false is ok

const pn2 = new PhoneNumber( '+551175757575', 'ZZ' );
console.log(pn2.isMobile()); // returns true, its wrong, it must return false
```

**Comment by chris-findlay** [comment]
This the same on the Google libPhone demo: https://giggsey.com/libphonenumber/?phonenumber=%2B551175757575&country=ZZ&language=&region=
Raise it against the root library.
