### ISSUE TITLE
`getSupportedCallingCodes` insufficient due to not being unique

### ISSUE THREAD

**Issue by chris-findlay** [grantila/awesome-phonenumber#35]
`libPhoneNumber` has both `getSupportedCallingCodes` and `getSupportedRegions` - the latter being suitable for a country selector as all its 246 entries are unique, unlike the 224 entries from the former.

It'd be really nice to expose both functions, as the missing one is more useful in my case, since `pn.getSupportedCallingCodes().map(x => pn.getRegionCodeForCountryCode(x))` is both incomplete and not entirely ISOAlpha2 - there are several `001` entries in there too.

**Comment by grantila** [comment]
Looks great!

**Comment by grantila** [comment]
(and a great PR following code style etc, big thanks!)
