### ISSUE TITLE
Feature request - easily get IDC

### ISSUE THREAD

**Issue by mweiczorek** [grantila/awesome-phonenumber#39]
Hi,

It would be nice if there were an easy way to get the ICD (international dialing code) from the number.

Currently, I have to do this:
```
pn.getNumber('international').split(' ')[0].replace(/^\+/, '')
```
Would be nice to have that available:
```
pn.getNumber('idc')
```

**Comment by avimar** [comment]
So, you want the country code?

There's currently a function for getting the Alpha-2 country code, e.g.
pn.getRegionCode( );               // -> 'SE'

So you can actually use that with the built-in converter:
`PhoneNumber.getCountryCodeForRegionCode(pn.getRegionCode())`

**Comment by grantila** [comment]
You're absolutely right @avimar, I'll add that as its own function...

**Comment by mweiczorek** [comment]
Thanks for adding this - the alternative was a bit verbose. I should add that this method is returning a number rather than a string - the TypeScript definition file says `string`.

**Comment by grantila** [comment]
You're absolutely right @mweiczorek I'm fixing it, thanks for letting me know!
