### ISSUE TITLE
Fatal error occurs when phone number is NULL when using getNumber function

### ISSUE THREAD

**Issue by tfrancois** [grantila/awesome-phonenumber#40]
In order to gracefully handle conditions where the phone number passed into the module is a NULL OR numeric value, the returned response/result should probably be NULL.

Currently, the following fatal error is returned (extremely problematic in code with no error handling):

```
TypeError: Cannot read property 'charAt' of null
at new Y (...\awesome-phonenumber\lib\index.js:481:146)
```

It's better to have the result of this condition be NULL and not perform the charAt enumeration or other evaluation of user input.  Furthermore, in most cases, the result of null expressions usually result in null responses/result.

Sometimes it is not always possible for developers to anticipate or perform pre-validation of all input from end users, in this case phone numbers, including null or empty values.

UPDATE:
The following also produces the same error!
```
 var pn = new PhoneNumber('(229) 596-4236', 'US');
 console.log(pn.getNumber('significant'));
```

**Comment by grantila** [comment]
The example works fine and produces no error: https://runkit.com/embed/103i1kb5j7we

Returning `null` for invalid input arguments is never gonna happen in `awesome-phonenumber`. Invalid input should throw, but I agree that the error message is not optimal and should be more clear. But it will throw of course, and you have to catch that.
