### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by ishigo1987** [grantila/awesome-phonenumber#43]
```
const PhoneNumber = require( 'awesome-phonenumber' );

const pn = new PhoneNumber( '+237697644414', 'SE' );
console.log(pn.isValid()) // return true it's not correct +237697644414 is a Cameroonian number
```

**Comment by grantila** [comment]
The second (semi-optional) `regionCode` argument is a hint, not an enforcement, in this case.

If you specify a complete e164 phone number (`+`-prefixed), the `regionCode` is a hint which may be ignored.
If you however specify a phone number on a local format, the `regionCode` is required and will be used.

If you want to be sure what country _actually_ holds the parsed number, invoke `.getRegionCode()` on the returned phone number object. It will in this case return `"CM"`.
