### ISSUE TITLE
New phone numbers in Kyrgyzstan

### ISSUE THREAD

**Issue by Evald24** [grantila/awesome-phonenumber#45]
Hi, new phone numbers in Kyrgyzstan:
+996 990 000 000
+996 995 000 000
+996 996 000 000
+996 997 000 000
+996 998 000 000
+996 999 000 000
https://giggsey.com/libphonenumber/?phonenumber=%2B996997123456&country=KG

**Comment by grantila** [comment]
This should have been taken care of by libphonenumber 8.11.0 and awesome-phonenumber 2.23 from 2nd Dec. Are you sure the latest version still fails on this? And please make sure libphonenumber supports it. awesome-phonenumber has no own parsing/validation of phone numbers.

**Comment by grantila** [comment]
Works fine in 2.25 anyway:

```
{
    "number": {
        "input": "+996990000000",
        "international": "+996 990 000 000",
        "national": "0990 000 000",
        "e164": "+996990000000",
        "rfc3966": "tel:+996-990-000-000",
        "significant": "990000000"
    },
    "regionCode": "KG",
    "valid": true,
    "possible": true,
    "canBeInternationallyDialled": true,
    "type": "mobile",
    "possibility": "is-possible"
}
```
