### ISSUE TITLE
New phone numbers in nigeria region is not being validated

### ISSUE THREAD

**Issue by chirag-sa** [grantila/awesome-phonenumber#46]
Hello, I am using awesome-phonenumber in my current project and validating phone numbers with this plugin

but nowadays I am facing issues after new phone number series is introduced in a particular region.

not valid phone number ex: +234801*****54, I have tried updating the package to the latest version.

`"awesome-phonenumber": "^2.24.0",`
**Code Snapshot:**

`
static phnValidate(c: FormControl): ValidationErrors {
    const num = c.value;
    let isValid = false;
    const pn = new awesomePhonenumber(num != null ? num : '+91');
    if (pn.isValid() && pn.isMobile()) {
      isValid = true
    }
    const message = {
      'phoneNumber': {
        'message': 'Phone Number is not valid'
      }
    };
    return isValid ? null : message;
  }
`
Error screenshot:

![image](https://user-images.githubusercontent.com/40169580/72608126-07d43e00-3948-11ea-9afb-df0b8f916b2c.png)

Valid phone number screenshot:
![image](https://user-images.githubusercontent.com/40169580/72608209-3b16cd00-3948-11ea-8d36-6fcd92876ba7.png)

**Comment by grantila** [comment]
The actual phone number validation is done by the underlying [libphonenumber](https://github.com/google/libphonenumber) so I'm afraid you'll have to bring up that issue with them.

**Comment by grantila** [comment]
Btw, this was released in the [libphonenumber 8.11.2](https://github.com/google/libphonenumber/blob/master/release_notes.txt) which reflects awesome-phonenumber 2.25
