### ISSUE TITLE
Returning 001 in region code

### ISSUE THREAD

**Issue by digvijay-r** [grantila/awesome-phonenumber#47]
While I was getting region code for mobile number +979998889998, the Api is returning region code 001 in response in Number type.
 I was expecting a string of region code.

**Comment by grantila** [comment]
According to https://en.wikipedia.org/wiki/List_of_country_calling_codes 979 is not really a region, but a special international prefix. The result "001" is actually a string (otherwise it would be `1`), which libphonenumber responds for "non-region regions"...
