### ISSUE TITLE
AsYouType formatting issues

### ISSUE THREAD

**Issue by mousedownmike** [grantila/awesome-phonenumber#49]
The As You Type functionality doesn't appear to work as documented in the README.md file.  When I execute a `removeChar()` earlier in the format, the formatting seems to break down.  I made the assumption that:

- `.removeChar()` would remove any formatting that was inserted AND a phone number digit.  Essentially this would be like an "undo".  That doesn't seem to be the case, it just removes the last character.
- I assumed that adding characters after removing characters would continue the formatting but that doesn't appear to be the case.

The following is my Jest test that replicates the README example but with actually passing values.

```typescript
import PhoneNumber from 'awesome-phonenumber';

describe('PhoneNumber', () => {
  test('#getAsYouType()', () => {
    const ayt = PhoneNumber.getAsYouType('SE');
    expect(ayt.addChar('0')).toEqual('0');
    expect(ayt.addChar('7')).toEqual('07');
    expect(ayt.addChar('0')).toEqual('070');
    expect(ayt.addChar('7')).toEqual('070-7');
    expect(ayt.addChar('1')).toEqual('070-71');
    expect(ayt.addChar('2')).toEqual('070-712');
    expect(ayt.addChar('3')).toEqual('070-712 3');
    expect(ayt.removeChar()).toEqual('070-712 '); // Trailing space not expected
    expect(ayt.removeChar()).toEqual('070-712');
    expect(ayt.addChar('3')).toEqual('070-7123'); // Expected '070-712 3'
    expect(ayt.addChar('4')).toEqual('070-71234');
    expect(ayt.addChar('5')).toEqual('070-712345');
    expect(ayt.addChar('6')).toEqual('070-7123456');
    expect(ayt.removeChar()).toEqual('070-712345');
    expect(ayt.addChar('7')).toEqual('070-7123457');
  });
});

```
I'm curious if this is a bug or if I'm misinterpreting the expected use of As You Type.

**Comment by grantila** [comment]
I consider this a bug too, thanks for the report
