### ISSUE TITLE
Missing isValidForRegion()

### ISSUE THREAD

**Issue by EveX1** [grantila/awesome-phonenumber#50]
When i try to validated `e164` formatted number with typo in the prefix, I got some weird results.

eg:

- Given a valid french mobile number: `+33 6 12 34 56 78`
- Say there is a typo in prefix (missing `3`): `+3 6 12 34 56 78`

No matter I pass the correct region in the constructor, the number is still valid (but with a Hungarian prefix):
```js
new PhoneNumber("+3 6 12 34 56 78").isValid(); // true
new PhoneNumber("+3 6 12 34 56 78", "FR").isValid(); // true
new PhoneNumber("+3 6 12 34 56 78", "FR").getNumber(); // +3612345678
new PhoneNumber("+3 6 12 34 56 78", "FR").getNumber('national'); // (06 1) 234 5678
new PhoneNumber("+3 6 12 34 56 78", "FR").getRegionCode(); // HU
```

But as I can be seen [here](https://giggsey.com/libphonenumber/index.php?phonenumber=%2B3+6+12+34+56+78&country=FR&language=&region=) the function `isValidNumberForRegion()` returns `false`.

If it were possible to add this function or any check in an instance if region is given to this (awesome ^^) lib, that would be great.

I'm not sure I can do it myself, but I was thinking something like:
```js
function isValidNumberForRegion(regionCode) {
  if(this.getRegionCode() !== regionCode) return false;
  return true;
}
```

Honestly it's my first time digging into a lib's code, I'm a bit confused.

**Comment by grantila** [comment]
The region code [is ignored](https://github.com/grantila/awesome-phonenumber#detect-country) if the phone number entered is on e164 format (where spaces are removed/trimmed), so this is technically not a bug. The region is only needed if the phone number is entered on a local format.

So, if you input +36, that's a Hungarian number, spaces are ignored - that's for *output* formatting, not for *input* detection.

If you're using this in a UI (where typos can be made), I'd suggest switching the country when the phone number changes, and not depending on a country field to be correct.

**Comment by EveX1** [comment]
I'm not saying there is a bug in the lib and I know it is ignored if E164 formated numbers are given. All I say is that it can be useful to have a check done if country is given, or have a function (like in the original lib) that check if a given number is valid for a given region/country.

I gave example of what can be received but I work on a server-side project where I can't trust any given entries nor I have access to the code on the client/front side. So I must check every phone number to be sure they are valid and that includes the region/country given for those numbers.

I've already done a validation function for number/country in top of your lib, using the available methods, but I though it would be a nice feature to add.

It's seems you don't want to and that's fine by me. :)

**Comment by sean6bucks** [comment]
While i see this is the expected behaviour, for what it's worth I also think this would be a great addition/feature as well. If you are going to have the ability to add an explicit region code in the `PhoneNumber` constructor (specifying that you know that the phone number should be scoped to a specific region/country limitation), why would you ignore it when checking validity.
