### ISSUE TITLE
CountryCodes for some countries are wrong

### ISSUE THREAD

**Issue by SrgSteak** [grantila/awesome-phonenumber#52]
console.log(PhoneNumber.getExample('AG').getNumber()); // e.g. +12684601234
console.log(PhoneNumber.getExample('AG').getCountryCode()); // 1

but it should be 1268
for Jamaika, it should be 1876
there are several others.

also, extracting the countryCode doesn't work with those countries.

**Comment by grantila** [comment]
This is a bug in the upstream [libphonenumber](https://github.com/google/libphonenumber) unfortunately.
