### ISSUE TITLE
Leading 0 added in national number

### ISSUE THREAD

**Issue by NicoSantilli** [grantila/awesome-phonenumber#63]
Hello there!

I've been using your library and noted that there's a leading 0 added in the number for some regions, for example Argentina or India.

**Argentina example:**
If the user inputs their number, let's say **1112345678** we expect to show the national number like **11 1234-5678** but the result is **011 1234-5678" while the international number is correctly displayed as **+54 11 1234-5678**.

```javascript
{
    "number": {
        "input": "01112345678",
        "international": "+54 11 1234-5678",
        "national": "011 1234-5678",
        "e164": "+541112345678",
        "rfc3966": "tel:+54-11-1234-5678",
        "significant": "1112345678"
    },
    "regionCode": "AR",
    "valid": true,
    "possible": true,
    "canBeInternationallyDialled": true,
    "type": "fixed-line",
    "possibility": "is-possible"
}
```

Please note that the leading 0 although will work it's not expected.

Thanks in advance.

**Comment by grantila** [comment]
Interesting, this must be because of how google libphonenumber works, so please check why that is, if it's unexpected, there's likely a good explanation 👍 

I'm not adding it anyway, maybe the libhonenumber [FAQ](https://github.com/google/libphonenumber/blob/master/FAQ.md) explains it.
