### ISSUE TITLE
ayt.reset() fails to reset when not provided a new number

### ISSUE THREAD

**Issue by stevegcarpenter** [grantila/awesome-phonenumber#64]
There are situations where I want to clear/reset the as you type number, but do not actually have a new number. Currently, calling the `ayt.reset()` method will update the number only if a new number is provided to replace the existing one. Here is a codesandbox where I've logged the values demonstrating this: https://codesandbox.io/s/nifty-forest-98eo5?file=/src/App.tsx

EDIT:
It looks like calling:

`ayt.reset()` followed by `ayt.addChar('')` will clear the internal number properly.

**Comment by grantila** [comment]
Thanks for the bug report and excellent example!
