### ISSUE TITLE
Fatal error after updating to 2.62.0

### ISSUE THREAD

**Issue by aleksandrlat** [grantila/awesome-phonenumber#67]
We receive same error as here https://github.com/grantila/awesome-phonenumber/issues/66#issuecomment-927143632

Object.defineProperty called on non-object
Call Stack
 eval
  node_modules/awesome-phonenumber/index.js:3:8
 ./node_modules/awesome-phonenumber/index.js
  vendor.js:3774:1
 Object.options.factory
  runtime.js:675:31
 __webpack_require__
  runtime.js:36:33
 fn
  runtime.js:346:21

Creating new issue because https://github.com/grantila/awesome-phonenumber/issues/66 is closed

**Comment by aleksandrlat** [comment]
Looks like nothing is exported from from `require( './lib' )` now or `require( './lib' ).PhoneNumber` does not exist anymore
![image](https://user-images.githubusercontent.com/3708309/135155441-b59e239e-cb51-46bd-b70c-58e397073c37.png)

Looks like upgrade to new closure compiler didn't work well.

**Comment by bgneu** [comment]
Facing a similar issue using this package in React Native.

**Comment by grantila** [comment]
I think this is fixed now. I've made a small webpack example where it runs fine.
