### ISSUE TITLE
Custom formatter and other number compoments

### ISSUE THREAD

**Issue by ryc16** [grantila/awesome-phonenumber#7]
Hi, 
#1, is it possible to specify the different number formatter?

For example, currently, getNumber('international') for US number returns +1 999-999-9999. I would like to display in ie +1 (999) 999-9999
#2. can it parse number into Area Code or Extension if exist?

Thanks & regards

**Comment by grantila** [comment]
The 'international' format is an _international format_. If you don't use that, the format will be your own custom format, non-standard. If this is what you want, you need to perform this manually, see https://github.com/googlei18n/libphonenumber/issues/46 for the upstream question. Reading through that discussion, you'll see that this doesn't fit all the worlds phone numbers. The getLengthOfNationalDestinationCode approach could be used (although awesome-phonenumber currently doesn't export it).

If this is supposed to be a feature for US phone numbers, would it suffice to use the international format and regex format it like this?

```js
'+1 999-999-9999'.replace( / (\d+)-/, ( _, area ) => ` (${area}) ` )
```
