### ISSUE TITLE
IE11. Const must be initialized

### ISSUE THREAD

**Issue by suyundukov** [grantila/awesome-phonenumber#71]
After upgrading package from v2.58.0 to v2.64.0 I get fatal error `Const must be initialized` on Internet Explorer. It complains on this line:

```js
function i(d){const t=[];let i=0;for(const e in d)t[i++]=d[e];return t}
```

I suppose something broke in v2.62.1, because everything works as expected on v2.62.0 and lower. The issue is reproducible with versions starting from v2.62.1.

**Comment by WTDuck** [comment]
After hours wondering who to blame for this `Const must be initialized` on IE11, I have a solution for Vue/Nuxt users

```
build: {
    transpile: ['awesome-phonenumber']
}
```
 As mentioned [here](https://stackoverflow.com/a/37800329), const inside `for-in / for-of` are not IE11 compatible
