### ISSUE TITLE
Breaking change in version 2.62.1

### ISSUE THREAD

**Issue by TheBananaGuy** [grantila/awesome-phonenumber#73]
**Node version:** 14.17.5
**NPM version:** 7.19.1
**Environment:** plain old JavaScript / ES5

@grantila re-opening the [initial issue](https://github.com/grantila/awesome-phonenumber/issues/70) that I posted.
version **2.63.0** didn't fix the issue, neither did **2.64.0**

We cannot use PhoneNumber as a module with `import` or `require`, only the old-school way by just copying the `index.js` directly from the package's `/lib` folder and adidng it via script tags in our template.

As long as the script from version **2.62.0 and below** was included in a given HTML template, the following did work anywhere in any `.js` file within the same template:
```JavaScript
var pn = PhoneNumber(phoneNum, country);
```
But it doesn't now, and we get an `Uncaught ReferenceError: PhoneNumber is not defined` error instead...

**NB!**
Please keep in mind that this is within ES5, with the assumption that no `const`s or `let`s exist.

**Comment by grantila** [comment]
I have [a webpack project](https://github.com/grantila/awesome-phonenumber/tree/master/webpack) built and tested in the pipeline which works fine.

You'll have to provide an example repo where this is failing for me to debug. Also, if you want to support ancient browsers, you'll likely need to transpile the javascript down using e.g. babel.
