### ISSUE TITLE
Export as es module

### ISSUE THREAD

**Issue by tlouisse** [grantila/awesome-phonenumber#74]
Hi,

Thanks for making this great package. It seems to be better than the original `google-libphonenumber`, both in terms of performance and developer experience.

What I was wondering, **would it be possible to add an esm output that allows for running this inside the browser as well**?

If appreciated, I could do a PR for this. I have a local version running of this, that could be added to the current gulp task. 
The build output could then be added as an export map:
```js
"exports": {
  "./": {
    "require": "./index.js",
    "default": "./index-esm.mjs",
  }
}
```

In this way, I could use it in a browser context as:

```js
import PhoneNumber from 'awesome-phonenumber';
```

and for NodeJS/commonjs it would stay as is:

```js
const PhoneNumber = require( 'awesome-phonenumber' );
```

**Comment by grantila** [comment]
I'm not sure I follow; what makes this not work in a browser today? Using import should work just fine (at least if using a bundler like webpack). The export should work in both cases. Or do you mean without a bundler altogether?

**Comment by grantila** [comment]
Regardless @tlouisse, feel free to make a PR and let me have a look

**Comment by tlouisse** [comment]
Hi, thanks for the reply. I mean without a bundler indeed. I want to use it inside a web component (an input that validates/formats phone numbers). This web component is shipped as its own package and should be able to work without a "build step".

You can expect a pull request in the coming weeks when I'm picking this up again 👍

**Comment by vrumjantsev** [comment]
@tlouisse hi, any update on that?

**Comment by tlouisse** [comment]
> @tlouisse hi, any update on that?

Hi, I will try to look into it in the coming days :)

**Comment by tlouisse** [comment]
@grantila I added the pr for this: https://github.com/grantila/awesome-phonenumber/pull/77

Let me know if this works for you!

**Comment by tlouisse** [comment]
@grantila any update on this?

**Comment by grantila** [comment]
I had the idea of changing the API while doing this, and everything ended up a lot more complicated, e.g. rollup didn't handle named exports well (from the closure-compiled output). But it's all finally working well, thanks for the work on this!

**Comment by grantila** [comment]
For reference of the API change; the `new` construction is deprecated, and the library now exports only named functions, making it more _functional_ and easy to compose.
Under the hood, the old API is still there, but removed from the TypeScript typings.

**Comment by tlouisse** [comment]
Nice! Thanks a lot @grantila
