### ISSUE TITLE
New indian numbers series are not supported 

### ISSUE THREAD

**Issue by avtaniket** [grantila/awesome-phonenumber#75]
These are newly indian numbers series which are not supported by this library

- 62XXXXXXXX Series
- 63XXXXXXXX Series
- etc

**Comment by grantila** [comment]
This library uses Google's [libphonenumber](https://github.com/google/libphonenumber) and has no phone number parsing itself. It seems this [is already supported](https://issuetracker.google.com/issues/117231938) but you can [create an issue](https://issuetracker.google.com/issues/new?component=192347&pli=1&template=829703) there if you still believe it's handled wrong.
