### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by bessaleh** [grantila/awesome-phonenumber#8]
Hello,
I tested your API and I found that when I make a request like this
`var body = new AwsomePhone( "0652648569xx", "FR");`
or with that number 
`065254(6569xx`
`065254(6569]xx`
I got this
```
{
  "number": {
    "input": "0652546569xx",
    "international": "+33 6 52 54 65 69",
    "national": "06 52 54 65 69",
    "e164": "+33652546569",
    "rfc3966": "tel:+33-6-52-54-65-69",
    "significant": "652546569"
  },
  "regionCode": "FR",
  "valid": true,
  "possible": true,
  "type": "mobile",
  "possibility": "is-possible"
}
```

Best regards

**Comment by grantila** [comment]
I assume you expect this to fail? It's not an odd assumption, but `awesome-phonenumber` performs no extra checks on top of Google's `libphonenumber`, so if they accept it, `awesome-phonenumber` will too.
