### ISSUE TITLE
TypeScript definitions don't match actual return types

### ISSUE THREAD

**Issue by lessp** [grantila/awesome-phonenumber#82]
Heya, thanks for the library!

Ran into an issue where some methods actually return `undefined` although the type definitions specify them as always returning a value.

More specifically these:
```
getNumber('national'): string | undefined           // specified as : string;
getType(): PhoneNumberTypes | undefined             // specified as : PhoneNumberTypes;
canBeInternationallyDialled():  boolean | undefined // specified as : boolean;
getNumberFrom(...): <-- throws
```

Reproduced here:
https://codesandbox.io/s/wizardly-jennings-68wdiq?file=/src/index.ts:258-285

**Comment by grantila** [comment]
The API is heavily rewritten in v4; much simpler.

Please take a look and see if this is still an issue, if so, please re-open!
