### ISSUE TITLE
Declaring valid number as invalid

### ISSUE THREAD

**Issue by FrikkieRetro** [grantila/awesome-phonenumber#9]
Hi,

When validating any number that starts with  085 in the ZA region, these numbers are marked as invalid, however, these numbers are valid.

Any reason for this?

**Comment by grantila** [comment]
Try with the latest version (1.1.3) which uses libphonenumber 7.7.5. If it's still a problem, you'll need to report it upstream, since it's a problem in libphonenumber: https://github.com/googlei18n/libphonenumber
