### ISSUE TITLE
ES5 compatibility

### ISSUE THREAD

**Issue by al007** [grantila/awesome-phonenumber#91]
Any plans to make the lib ES5 compatible? If not, would you like to explicitly write this in the description and in the lib comparison table? As of now, the latest version of google-libphonenumber is ES5 compatible.

**Comment by grantila** [comment]
ES5 is ancient, afaik only required by IE11, which Microsoft stopped supporting even security updates 3 years ago. Sorry, but it's time to ignore this, it fits better in history books than in README's.

If you for some reason still need it, a) question if you actually do, and b) use babel or something to transpile.
