### ISSUE TITLE
Awesome phone number validation is different from google-libphonenumber

### ISSUE THREAD

**Issue by arunragha89** [grantila/awesome-phonenumber#97]
HI Team,

When i validated below numbers with awesome phone numbers, the numbers are invalid but with google-libphonenumber lib it is shown as valid.   Though both lib use the same libphone number version how is this validation differnt 
+979109999999
+80019999999 
+870309999999
+881009999999
+979189999999 
+979109999999

Thanks

**Comment by grantila** [comment]
Which one is correct? +979 isn't a valid prefix, is it? Not +800 neither.

Check here: https://en.wikipedia.org//wiki/List_of_mobile_telephone_prefixes_by_country

If you _know_ these are valid, and have references to back that up, I'd be interested.
