### ISSUE TITLE
parsePhoneNumber response marked as invalid

### ISSUE THREAD

**Issue by j-christoffersen** [grantila/awesome-phonenumber#98]
Version: 5.2.0

Running the following gives an invalid and presumably incorrect result
```
parsePhoneNumber("0740521234", { regionCode: "US" })
```

This is the result:
```
{
  number: {
    input: '0740521234',
    international: '+1 0740521234',
    national: '0740521234',
    e164: '+10740521234',
    rfc3966: 'tel:+1-0740521234',
    significant: '0740521234'
  },
  regionCode: 'US',
  valid: false,
  possible: true,
  canBeInternationallyDialled: true,
  type: 'unknown',
  possibility: 'is-possible',
  typeIsMobile: false,
  typeIsFixedLine: false,
  countryCode: 1
}
```

Seems like `valid` should be `true` here, but regardless the shape of the response is neither `ParsedPhoneNumberValid` nor `ParsedPhoneNumberInvalid` as defined in the readme

**Comment by grantila** [comment]
Fixed in 5.3.0

**Comment by timm-stelzer-e-farm** [comment]
Regression in `5.10.0`, same input and incorrect result as OP.

**Comment by grantila** [comment]
This is not a valid US phone number, is it?

**Comment by timm-stelzer-e-farm** [comment]
True, numbers can't lead with a `0`. My bad, I assumed if `valid===false`, we don't get the other fields.
